
version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ezyops123
      MYSQL_DATABASE: test_db1
      MYSQL_USER: ezyops
      MYSQL_PASSWORD: ezyops123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: